export { quantize, roundHalfUp } from './numeric/round.js';

export { TAXONOMY, aliasesOf, canonicalize, getEntry, relatedTo } from './taxonomy/index.js';
export type { SkillCategory, Taxonomy, TaxonomyEntry } from './taxonomy/index.js';

export {
  assertValidSpan,
  detectSections,
  extractAttributes,
  extractCertifications,
  extractEducation,
  extractSkills,
  extractYearsExperience,
  segmentLines,
} from './extraction/index.js';
export type {
  AttributeKind,
  CertificationAttribute,
  DegreeLevel,
  EducationAttribute,
  ExtractedAttribute,
  ExtractionOptions,
  LineSegment,
  Section,
  SectionName,
  SkillAttribute,
  SkillExtractionMatchType,
  SourceSpan,
  YearsExperienceAttribute,
} from './extraction/index.js';

export {
  ALIAS_SUBSCORE,
  DEGREE_LADDER,
  DIMENSION_IDS,
  EXACT_SUBSCORE,
  NONE_SUBSCORE,
  RELATED_SUBSCORE,
  SENIORITY_LADDER,
  SENIORITY_YEAR_THRESHOLDS,
  bestDegreeLevel,
  buildExplanation,
  educationCertsSubscore,
  evaluateEligibility,
  experienceRelevanceSubscore,
  hasCertification,
  inferSeniorityLevel,
  matchAllSkillRequirements,
  matchSkillRequirement,
  rankCandidates,
  scoreCandidate,
  senioritySubscore,
  skillsSubscore,
  totalYearsExperience,
} from './scoring/index.js';
export type {
  Candidate,
  DimensionContribution,
  DimensionId,
  EducationCertsDimensionSpec,
  EducationRequirement,
  EligibilityResult,
  ExperienceDimensionSpec,
  ExperienceRequirement,
  Explanation,
  GapItem,
  Job,
  MatchType,
  RankedCandidates,
  ScoreComposition,
  ScoreResult,
  SemanticMatcher,
  SeniorityDimensionSpec,
  SeniorityLevel,
  SeniorityRequirement,
  SkillMatchResult,
  SkillRequirement,
  SkillRequirementMatch,
  SkillsDimensionSpec,
  StrengthItem,
  UnmetRequirement,
} from './scoring/index.js';
