import type { Taxonomy, TaxonomyEntry } from './types.js';

/**
 * Seed vocabulary for the thin vertical slice (ADR-011). Software, data and
 * common business/analyst skills. Not exhaustive — extending it is additive
 * (new entries, new aliases) and does not require renaming existing ids,
 * which is why canonical ids are the stable join key everywhere else in the
 * engine rather than labels.
 *
 * `related` links are directed and hand-curated for the cascade's step 3
 * ("taxonomy-related", 0.70). They are deliberately conservative: two skills
 * are related only when a recruiter would plausibly credit one as partial
 * evidence of the other, not merely because they appear in similar job ads.
 */
const ENTRIES: readonly TaxonomyEntry[] = [
  // ---- Languages ----
  {
    id: 'javascript',
    label: 'JavaScript',
    category: 'language',
    aliases: ['js', 'ecmascript'],
    related: ['typescript', 'nodejs'],
  },
  {
    id: 'typescript',
    label: 'TypeScript',
    category: 'language',
    aliases: ['ts'],
    related: ['javascript'],
  },
  {
    id: 'python',
    label: 'Python',
    category: 'language',
    aliases: ['py'],
    related: ['pandas', 'django', 'flask'],
  },
  {
    id: 'java',
    label: 'Java',
    category: 'language',
    aliases: [],
    related: ['spring', 'spring-boot', 'kotlin'],
  },
  {
    id: 'csharp',
    label: 'C#',
    category: 'language',
    aliases: ['c#', 'c sharp', 'dotnet-lang'],
    related: ['dotnet', 'aspnet'],
  },
  { id: 'cpp', label: 'C++', category: 'language', aliases: ['c++'], related: ['c'] },
  { id: 'c', label: 'C', category: 'language', aliases: [], related: ['cpp'] },
  { id: 'go', label: 'Go', category: 'language', aliases: ['golang'], related: [] },
  { id: 'rust', label: 'Rust', category: 'language', aliases: [], related: [] },
  { id: 'ruby', label: 'Ruby', category: 'language', aliases: [], related: ['rails'] },
  { id: 'php', label: 'PHP', category: 'language', aliases: [], related: ['laravel'] },
  { id: 'swift', label: 'Swift', category: 'language', aliases: [], related: ['ios'] },
  {
    id: 'kotlin',
    label: 'Kotlin',
    category: 'language',
    aliases: [],
    related: ['java', 'android'],
  },
  { id: 'scala', label: 'Scala', category: 'language', aliases: [], related: ['spark', 'java'] },
  {
    id: 'r',
    label: 'R',
    category: 'language',
    aliases: ['r-lang', 'r-language'],
    related: ['statistics'],
  },
  {
    id: 'sql',
    label: 'SQL',
    category: 'language',
    aliases: [],
    related: ['postgresql', 'mysql', 'sql-server'],
  },
  {
    id: 'bash',
    label: 'Bash / Shell',
    category: 'language',
    aliases: ['shell', 'shell-scripting', 'sh'],
    related: ['linux'],
  },

  // ---- Frameworks ----
  {
    id: 'react',
    label: 'React',
    category: 'framework',
    aliases: ['reactjs', 'react.js'],
    related: ['javascript', 'nextjs'],
  },
  {
    id: 'angular',
    label: 'Angular',
    category: 'framework',
    aliases: ['angularjs'],
    related: ['typescript'],
  },
  {
    id: 'vue',
    label: 'Vue',
    category: 'framework',
    aliases: ['vuejs', 'vue.js'],
    related: ['javascript'],
  },
  {
    id: 'nextjs',
    label: 'Next.js',
    category: 'framework',
    aliases: ['next.js', 'next'],
    related: ['react'],
  },
  {
    id: 'nodejs',
    label: 'Node.js',
    category: 'framework',
    aliases: ['node', 'node.js'],
    related: ['javascript', 'express'],
  },
  {
    id: 'express',
    label: 'Express',
    category: 'framework',
    aliases: ['express.js', 'expressjs'],
    related: ['nodejs'],
  },
  { id: 'django', label: 'Django', category: 'framework', aliases: [], related: ['python'] },
  { id: 'flask', label: 'Flask', category: 'framework', aliases: [], related: ['python'] },
  { id: 'fastapi', label: 'FastAPI', category: 'framework', aliases: [], related: ['python'] },
  {
    id: 'spring',
    label: 'Spring',
    category: 'framework',
    aliases: [],
    related: ['java', 'spring-boot'],
  },
  {
    id: 'spring-boot',
    label: 'Spring Boot',
    category: 'framework',
    aliases: ['springboot'],
    related: ['spring', 'java'],
  },
  {
    id: 'rails',
    label: 'Ruby on Rails',
    category: 'framework',
    aliases: ['ruby on rails'],
    related: ['ruby'],
  },
  {
    id: 'dotnet',
    label: '.NET',
    category: 'framework',
    aliases: ['.net', 'dot net', 'net core', '.net core'],
    related: ['csharp', 'aspnet'],
  },
  {
    id: 'aspnet',
    label: 'ASP.NET',
    category: 'framework',
    aliases: ['asp.net'],
    related: ['dotnet', 'csharp'],
  },
  { id: 'laravel', label: 'Laravel', category: 'framework', aliases: [], related: ['php'] },

  // ---- Databases ----
  {
    id: 'postgresql',
    label: 'PostgreSQL',
    category: 'database',
    aliases: ['postgres', 'psql', 'pg'],
    related: ['sql'],
  },
  { id: 'mysql', label: 'MySQL', category: 'database', aliases: ['my sql'], related: ['sql'] },
  {
    id: 'sql-server',
    label: 'SQL Server',
    category: 'database',
    aliases: ['mssql', 'microsoft sql server', 't-sql', 'tsql'],
    related: ['sql'],
  },
  {
    id: 'oracle-db',
    label: 'Oracle Database',
    category: 'database',
    aliases: ['oracle db', 'plsql', 'pl/sql'],
    related: ['sql'],
  },
  { id: 'sqlite', label: 'SQLite', category: 'database', aliases: [], related: ['sql'] },
  { id: 'mongodb', label: 'MongoDB', category: 'database', aliases: ['mongo'], related: ['nosql'] },
  { id: 'redis', label: 'Redis', category: 'database', aliases: [], related: ['nosql'] },
  {
    id: 'elasticsearch',
    label: 'Elasticsearch',
    category: 'database',
    aliases: ['elastic search', 'elastic'],
    related: ['nosql'],
  },
  {
    id: 'dynamodb',
    label: 'DynamoDB',
    category: 'database',
    aliases: ['dynamo db'],
    related: ['nosql', 'aws'],
  },
  {
    id: 'cassandra',
    label: 'Cassandra',
    category: 'database',
    aliases: ['apache cassandra'],
    related: ['nosql'],
  },
  { id: 'nosql', label: 'NoSQL', category: 'database', aliases: [], related: ['mongodb'] },

  // ---- Cloud & DevOps ----
  {
    id: 'aws',
    label: 'Amazon Web Services',
    category: 'cloud',
    aliases: ['amazon web services'],
    related: ['cloud-computing'],
  },
  {
    id: 'azure',
    label: 'Microsoft Azure',
    category: 'cloud',
    aliases: ['microsoft azure'],
    related: ['cloud-computing'],
  },
  {
    id: 'gcp',
    label: 'Google Cloud Platform',
    category: 'cloud',
    aliases: ['google cloud', 'google cloud platform'],
    related: ['cloud-computing'],
  },
  {
    id: 'cloud-computing',
    label: 'Cloud Computing',
    category: 'cloud',
    aliases: [],
    related: ['aws', 'azure', 'gcp'],
  },
  {
    id: 'docker',
    label: 'Docker',
    category: 'devops',
    aliases: ['containerization'],
    related: ['kubernetes'],
  },
  {
    id: 'kubernetes',
    label: 'Kubernetes',
    category: 'devops',
    aliases: ['k8s'],
    related: ['docker'],
  },
  {
    id: 'terraform',
    label: 'Terraform',
    category: 'devops',
    aliases: [],
    related: ['infrastructure-as-code'],
  },
  {
    id: 'infrastructure-as-code',
    label: 'Infrastructure as Code',
    category: 'devops',
    aliases: ['iac'],
    related: ['terraform', 'ansible'],
  },
  {
    id: 'ansible',
    label: 'Ansible',
    category: 'devops',
    aliases: [],
    related: ['infrastructure-as-code'],
  },
  { id: 'jenkins', label: 'Jenkins', category: 'devops', aliases: [], related: ['ci-cd'] },
  {
    id: 'github-actions',
    label: 'GitHub Actions',
    category: 'devops',
    aliases: ['gh actions'],
    related: ['ci-cd'],
  },
  {
    id: 'ci-cd',
    label: 'CI/CD',
    category: 'devops',
    aliases: ['continuous integration', 'continuous deployment', 'ci/cd'],
    related: ['jenkins', 'github-actions', 'devops'],
  },
  {
    id: 'devops',
    label: 'DevOps',
    category: 'devops',
    aliases: [],
    related: ['ci-cd', 'docker', 'kubernetes'],
  },
  { id: 'linux', label: 'Linux', category: 'devops', aliases: ['unix'], related: ['bash'] },
  { id: 'git', label: 'Git', category: 'tool', aliases: [], related: ['github', 'ci-cd'] },
  { id: 'github', label: 'GitHub', category: 'tool', aliases: [], related: ['git'] },
  {
    id: 'microservices',
    label: 'Microservices',
    category: 'devops',
    aliases: ['microservice architecture'],
    related: ['docker', 'kubernetes'],
  },
  {
    id: 'rest-api',
    label: 'REST APIs',
    category: 'devops',
    aliases: ['rest', 'restful', 'restful api', 'rest api'],
    related: ['api-design'],
  },
  { id: 'graphql', label: 'GraphQL', category: 'devops', aliases: [], related: ['api-design'] },
  {
    id: 'api-design',
    label: 'API Design',
    category: 'devops',
    aliases: [],
    related: ['rest-api', 'graphql'],
  },
  {
    id: 'system-design',
    label: 'System Design',
    category: 'devops',
    aliases: [],
    related: ['microservices', 'api-design'],
  },

  // ---- Data / ML ----
  { id: 'pandas', label: 'Pandas', category: 'data', aliases: [], related: ['python', 'numpy'] },
  { id: 'numpy', label: 'NumPy', category: 'data', aliases: [], related: ['python', 'pandas'] },
  {
    id: 'scikit-learn',
    label: 'scikit-learn',
    category: 'data',
    aliases: ['sklearn', 'scikit learn'],
    related: ['machine-learning', 'python'],
  },
  {
    id: 'tensorflow',
    label: 'TensorFlow',
    category: 'data',
    aliases: ['tf'],
    related: ['machine-learning', 'deep-learning'],
  },
  {
    id: 'pytorch',
    label: 'PyTorch',
    category: 'data',
    aliases: [],
    related: ['machine-learning', 'deep-learning'],
  },
  {
    id: 'machine-learning',
    label: 'Machine Learning',
    category: 'data',
    aliases: ['ml'],
    related: ['data-science', 'deep-learning'],
  },
  {
    id: 'deep-learning',
    label: 'Deep Learning',
    category: 'data',
    aliases: ['dl'],
    related: ['machine-learning'],
  },
  {
    id: 'data-science',
    label: 'Data Science',
    category: 'data',
    aliases: [],
    related: ['machine-learning', 'statistics'],
  },
  {
    id: 'statistics',
    label: 'Statistics',
    category: 'data',
    aliases: ['stats'],
    related: ['data-science'],
  },
  {
    id: 'spark',
    label: 'Apache Spark',
    category: 'data',
    aliases: ['apache spark', 'pyspark'],
    related: ['big-data'],
  },
  {
    id: 'hadoop',
    label: 'Hadoop',
    category: 'data',
    aliases: ['apache hadoop'],
    related: ['big-data'],
  },
  {
    id: 'big-data',
    label: 'Big Data',
    category: 'data',
    aliases: [],
    related: ['spark', 'hadoop'],
  },
  {
    id: 'airflow',
    label: 'Apache Airflow',
    category: 'data',
    aliases: ['apache airflow'],
    related: ['etl'],
  },
  {
    id: 'dbt',
    label: 'dbt',
    category: 'data',
    aliases: ['data build tool'],
    related: ['etl', 'sql'],
  },
  {
    id: 'etl',
    label: 'ETL',
    category: 'data',
    aliases: ['extract transform load'],
    related: ['data-warehousing', 'airflow'],
  },
  {
    id: 'data-warehousing',
    label: 'Data Warehousing',
    category: 'data',
    aliases: ['data warehouse'],
    related: ['etl'],
  },
  {
    id: 'tableau',
    label: 'Tableau',
    category: 'data',
    aliases: [],
    related: ['data-visualization'],
  },
  {
    id: 'power-bi',
    label: 'Power BI',
    category: 'data',
    aliases: ['powerbi'],
    related: ['data-visualization'],
  },
  {
    id: 'data-visualization',
    label: 'Data Visualization',
    category: 'data',
    aliases: ['dataviz'],
    related: ['tableau', 'power-bi'],
  },
  {
    id: 'excel',
    label: 'Microsoft Excel',
    category: 'data',
    aliases: ['ms excel', 'spreadsheets'],
    related: ['data-analysis'],
  },
  {
    id: 'data-analysis',
    label: 'Data Analysis',
    category: 'data',
    aliases: [],
    related: ['excel', 'sql', 'statistics'],
  },
  {
    id: 'ab-testing',
    label: 'A/B Testing',
    category: 'data',
    aliases: ['ab testing', 'split testing'],
    related: ['statistics'],
  },

  // ---- Testing ----
  {
    id: 'unit-testing',
    label: 'Unit Testing',
    category: 'testing',
    aliases: ['unit tests'],
    related: ['test-automation'],
  },
  {
    id: 'test-automation',
    label: 'Test Automation',
    category: 'testing',
    aliases: [],
    related: ['unit-testing'],
  },
  {
    id: 'jest',
    label: 'Jest',
    category: 'testing',
    aliases: [],
    related: ['javascript', 'unit-testing'],
  },
  {
    id: 'cypress',
    label: 'Cypress',
    category: 'testing',
    aliases: [],
    related: ['test-automation'],
  },
  {
    id: 'selenium',
    label: 'Selenium',
    category: 'testing',
    aliases: [],
    related: ['test-automation'],
  },
  {
    id: 'qa',
    label: 'Quality Assurance',
    category: 'testing',
    aliases: ['quality assurance'],
    related: ['test-automation'],
  },

  // ---- Design / mobile ----
  { id: 'figma', label: 'Figma', category: 'design', aliases: [], related: ['ui-ux-design'] },
  {
    id: 'ui-ux-design',
    label: 'UI/UX Design',
    category: 'design',
    aliases: ['ux design', 'ui design', 'ux/ui'],
    related: ['figma'],
  },
  {
    id: 'photoshop',
    label: 'Adobe Photoshop',
    category: 'design',
    aliases: ['adobe photoshop'],
    related: ['ui-ux-design'],
  },
  {
    id: 'ios',
    label: 'iOS Development',
    category: 'framework',
    aliases: ['ios development'],
    related: ['swift'],
  },
  {
    id: 'android',
    label: 'Android Development',
    category: 'framework',
    aliases: ['android development'],
    related: ['kotlin'],
  },

  // ---- Methodology / project tools ----
  {
    id: 'agile',
    label: 'Agile',
    category: 'methodology',
    aliases: [],
    related: ['scrum', 'kanban'],
  },
  { id: 'scrum', label: 'Scrum', category: 'methodology', aliases: [], related: ['agile'] },
  { id: 'kanban', label: 'Kanban', category: 'methodology', aliases: [], related: ['agile'] },
  {
    id: 'project-management',
    label: 'Project Management',
    category: 'business',
    aliases: [],
    related: ['agile', 'stakeholder-management'],
  },
  {
    id: 'product-management',
    label: 'Product Management',
    category: 'business',
    aliases: [],
    related: ['agile', 'stakeholder-management'],
  },
  { id: 'jira', label: 'Jira', category: 'tool', aliases: [], related: ['agile'] },
  { id: 'confluence', label: 'Confluence', category: 'tool', aliases: [], related: ['jira'] },

  // ---- Business / analyst ----
  {
    id: 'business-analysis',
    label: 'Business Analysis',
    category: 'business',
    aliases: [],
    related: ['requirements-gathering', 'stakeholder-management'],
  },
  {
    id: 'requirements-gathering',
    label: 'Requirements Gathering',
    category: 'business',
    aliases: [],
    related: ['business-analysis'],
  },
  {
    id: 'stakeholder-management',
    label: 'Stakeholder Management',
    category: 'business',
    aliases: [],
    related: ['business-analysis'],
  },
  {
    id: 'financial-modeling',
    label: 'Financial Modeling',
    category: 'business',
    aliases: ['financial modelling'],
    related: ['excel'],
  },
  { id: 'salesforce', label: 'Salesforce', category: 'business', aliases: [], related: ['crm'] },
  { id: 'sap', label: 'SAP', category: 'business', aliases: [], related: ['erp'] },
  {
    id: 'erp',
    label: 'ERP Systems',
    category: 'business',
    aliases: ['erp systems'],
    related: ['sap'],
  },
  {
    id: 'crm',
    label: 'CRM Systems',
    category: 'business',
    aliases: ['crm systems'],
    related: ['salesforce'],
  },
  {
    id: 'marketing',
    label: 'Marketing',
    category: 'business',
    aliases: [],
    related: ['seo', 'content-strategy'],
  },
  {
    id: 'seo',
    label: 'SEO',
    category: 'business',
    aliases: ['search engine optimization'],
    related: ['marketing'],
  },
  {
    id: 'content-strategy',
    label: 'Content Strategy',
    category: 'business',
    aliases: [],
    related: ['marketing'],
  },
  {
    id: 'negotiation',
    label: 'Negotiation',
    category: 'business',
    aliases: [],
    related: ['stakeholder-management'],
  },
  {
    id: 'leadership',
    label: 'Leadership',
    category: 'business',
    aliases: [],
    related: ['project-management'],
  },
  {
    id: 'communication',
    label: 'Communication',
    category: 'business',
    aliases: [],
    related: ['stakeholder-management'],
  },
];

export const TAXONOMY: Taxonomy = {
  version: '1.0.0',
  entries: ENTRIES,
};
